%% Arrhenius fit

clearvars
close all
clc

% Add paths
addpath(genpath("src")); 
addpath("results");

%% Constants

k_B = 1.380649e-23;         % Boltzmann constant [J/K]
Av  = 6.02214076e23;        % Avogrado constant [1/mol]

%% Variables

Save_plots = false;
SaveDir = "figures/msd";

%% Load Water Data

[Diffusion_data, Mol_values] = io.load_msd_struct(...
    "data/msd", ... 
    Pattern="*.txt", ...
    Smooth=true, ...
    SmoothWindow=500);

%% Diffusion coefficient Fit

% Start and end times for diffusion fit
start_time       = 400; 
end_time         = 800; 

Diffusion_data  = analysis.fit_diffusion(...
    Diffusion_data, ...
    start_time, ...
    end_time);

% MSD plots per group
plotting.plot_msd(...
    Diffusion_data, ...
    Mol_values, ...
    Scale="linear", ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Diffusion Coefficient parameters

% Beta plot
plotting.plot_beta(...
    Diffusion_data, ...
    Mol_values, ...
    Scale="linear", ...
    LineAlpha=0.7, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

% Loading plot
plotting.plot_diffusion_loading(...
    Diffusion_data, ...
    LegendLocation="northeast",...
    Scale="linear", ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Arrhenius Fit

% Find Arrhenius coefficients
Diffusion_data = analysis.fit_arrhenius(...
    Diffusion_data, ...
    Mol_values, ...
    k_B, ...
    Av);

% Plot Arrhenius correlations for all sims
plotting.plot_arrhenius(...
    Diffusion_data, ...
    Mol_values, ...
    k_B, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

% Average Arrhenius coefficients per loading
Arrhenius_params = analysis.fit_arrhenius_averaged(...
    Diffusion_data, ...
    Mol_values, ...
    k_B, ...
    Av);

%  Plot average Arrhenius in one plot
plotting.plot_arrhenius_averaged(...
    Arrhenius_params, ...
    k_B, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Save Results

T = struct2table(Diffusion_data);
induvidual_Arrhenius_params = unique(T(:, {'H2O','H3O','Ea','Ea_kJmol','D0'}), 'rows');

% Display table
fprintf('\n  ========= Arrhenius Parameters (per H2O/H3O) =========\n\n');
disp(induvidual_Arrhenius_params);
fprintf('  ======================================================\n');

fprintf('\n  ============== Arrhenius  Parameters ==============\n\n');
disp(Arrhenius_params(:, {'Ea','Ea_kJmol','D0','RMSE'}));
fprintf('  ===================================================\n');

% Save to results directory
if ~isfolder('results'), mkdir('results'); end
save('results/Arrhenius_params.mat', 'Arrhenius_params');
fprintf('\nArrhenius parameters saved to results/Arrhenius_params.mat\n');



