%% Heatmap Analysis

clearvars
close all
clc

% Add paths
addpath("src");

%% Variables

Save_plots = true;
SaveDir = "figures/heatmaps/";

%% Load Heatmap Data

[Heatmap_data, Mol_values] = io.load_heatmap_struct(... 
    "data/heatmap_data", ... 
    Pattern="*.dat", ...
    Verbose=true);

%% Set plot opts

settings = {...
    'MOFFile', "data/UiO-66.xyz", ... 
    'MaxValue', 15, ...
    'HeatmapAlpha', 0.4, ...
    'AtomAlpha', 0.4, ...
    'MarkerSize', 3, ...
    'ShowMOF', false, ...
    'DisplayMode', 'off', ...
    'DPI', 300};

filter = {...
    'H2O', [], ... 
    'Temperature', [], ...
    'SamplingFreq', []};

style_slice = {...
    'ShowColorbar', true, ...
    'ShowTitle', false, ...
    'AxisSize', [380, 380], ...
    'FigSize', [500, 420], ...
    'FontSize', 12, ...
    'TitleFontSize', 14};

style_cube = {...
    'ShowColorbar', false, ...
    'ShowTitle', false, ...
    'AxisSize', [400, 400], ...
    'FigSize', [500, 460], ...
    'FontSize', 11, ...
    'TitleFontSize', 13};

%% Visualize 2D Heatmap slices

plotting.plot_2D_heatmap(Heatmap_data, ... 
    filter{:}, ... 
    settings{:}, ...
    style_slice{:}, ...
    PlotType="XYZ", ...
    Save=Save_plots, ... 
    SaveDir=SaveDir, ... 
    Verbose=true);

return

%% Visualize 3D Cube View

plotting.plot_2D_heatmap(Heatmap_data, ...
    filter{:}, ... 
    settings{:}, ...
    style_cube{:}, ...
    PlotType="3D", ...
    Save=Save_plots, ... 
    SaveDir=SaveDir, ... 
    Verbose=true);

%% Visualize ALL 2D slices + 3D cube (interactive viewing)

plotting.plot_2D_heatmap(Heatmap_data, ...
    H2O=[130], ...
    Temperature=[300], ...
    SamplingFreq=[], ...
    PlotType="all", ...
    MOFFile="data/UiO-66. xyz", ...
    MaxValue=15, ...
    HeatmapAlpha=0.4, ... 
    AtomAlpha=0.4, ...
    MarkerSize=3, ...
    ShowMOF=false, ...
    ShowColorbar=true, ... 
    ShowTitle=true, ...
    DisplayMode="interactive", ... 
    Save=false, ...
    Verbose=true);

%% Combine 2D slices into 3D heatmaps

Heatmap_data_3D = analysis.combine_heatmap_xyz(...
    Heatmap_data, ...
	GridSize=200, ...
	Method="linear", ...
	Verbose=true);

%% Visualize 3D Heatmaps - Isosurface (original)

plotting.plot_3D_heatmap(Heatmap_data_3D, ...
    Index=1, ...
    PlotType="isosurface", ...
    IsoValue=0.5, ...
    FaceColor='cyan', ...
    FaceAlpha=0.7, ...
    ShowSlices=false, ...
    Colormap="turbo", ...
    ShowMOF=true, ...
    AtomAlpha=0.4, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Visualize 3D Heatmaps - Scatter plot

plotting.plot_3D_heatmap(Heatmap_data_3D, ...
    Index=1, ...
    PlotType="scatter", ...
    MaxValue=20, ...
    HeatmapAlpha=0.75, ...
    MarkerSize=6, ...
    Downsample=10, ...
    Colormap="turbo", ...
    ShowMOF=true, ...
    AtomAlpha=0.4, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Visualize 3D Heatmaps - Both combined

plotting.plot_3D_heatmap(Heatmap_data_3D, ...
    Index=1, ...
    PlotType="both", ...
    IsoValue=0.3, ...
    FaceColor='cyan', ...
    FaceAlpha=0.3, ...
    MaxValue=20, ...
    HeatmapAlpha=0.4, ...
    MarkerSize=2, ...
    Downsample=10, ...
    Colormap="turbo", ...
    ShowMOF=true, ...
    AtomAlpha=0.4, ...
    Save=Save_plots, ...
    SaveDir=SaveDir);

%% Display Summary

fprintf('\n=== Heatmap Data Summary ===\n');
fprintf('2D slices loaded: %d\n', numel(Heatmap_data));
fprintf('3D heatmaps created: %d\n', numel(Heatmap_data_3D));

if ~isempty(Heatmap_data_3D)
    T3D = struct2table(Heatmap_data_3D);
    disp(T3D(:, {'name','H2O','temperature','sampling_freq'}));
end