%% PTFEL and Conductivity Analysis
% Streamlined workflow using existing Arrhenius parameters

clearvars
close all
clc

% Add paths
addpath(genpath("src"));
addpath("results");

%% Constants

k_B = 1.380649e-23;         % Boltzmann constant [J/K]
Av  = 6.02214076e23;        % Avogadro constant [1/mol]
h   = 6.62607015e-34;       % Planck constant [J s]
e   = 1.602176634e-19;      % Elementary charge [C]
R   = k_B*Av;               % Universal gas constant [J/mol K]

%% Variables

Save_plots = true;
SaveDir_ptfel = "figures/ptfel";
SaveDir_cond = "figures/conductivity";

% PT-FEL parameters
SamplingFreq_filter = 2;    % Only use 2fs simulations
V_cell = 20.8584^3;         % Unit cell volume [Angstrom^3]
a_hop = 2.45;               % Hopping distance [Angstrom]
kappa = 0.1;                % transmission coefficient

%% Load PTFEL Data (2fs only)

fprintf('\n=== Loading PTFEL Data (2fs only) ===\n');

[PTFEL_data, ~] = io.load_ptfel_struct(... 
    "data/ptfel", ...
    Pattern="ptfel_*.txt", ...
    SamplingFreq=SamplingFreq_filter, ...
    Verbose=false);

fprintf('Loaded %d PTFEL files (2fs simulations)\n', numel(PTFEL_data));

%% Extract Barriers and Fit Thermodynamics

fprintf('\n=== Extracting Barriers & Fitting DeltaH/DeltaS ===\n');

[PTFEL_params, PTFEL_data_processed] = analysis.extract_ptfel_thermodynamics(... 
    PTFEL_data, k_B, Av, ... 
    SavGolWindow=31, ...
    SavGolOrder=3);

fprintf('Extracted barriers for %d conditions\n', height(PTFEL_params));

% Display results
fprintf('\n  ============ PTFEL Activation Barriers ============\n\n');
disp(PTFEL_params);
fprintf('  ====================================================\n');

%% Load Existing Arrhenius Parameters

fprintf('\n=== Loading Arrhenius Parameters ===\n');

if isfile('results/Arrhenius_params.mat')
    load('results/Arrhenius_params.mat', 'Arrhenius_params');
    fprintf('Loaded Arrhenius parameters for %d loadings\n', height(Arrhenius_params));
else
    error('Arrhenius_params.mat not found.  Run Arrhenius. m first.');
end

%% Calculate Conductivity

fprintf('\n=== Calculating Conductivity ===\n');

Conductivity_data = analysis.calc_conductivity(...
    Arrhenius_params, ... 
    PTFEL_params, ... 
    V_cell=V_cell, ...
    a_hop=a_hop, ... 
    kappa=kappa, ...
    k_B=k_B, ... 
    h=h, ...
    e=e, ...
    temperatures=300:10:400, ...
    H3O_per_cell=4);

fprintf('Calculated conductivity for %d conditions\n', height(Conductivity_data));

% Convert J to kJ/mol for the table display
Conductivity_data.dH_kJmol = (Conductivity_data.dH_w * Av) / 1000; 
Conductivity_data.dS_JmolK = (Conductivity_data.dS_w * Av); 
Conductivity_data.sigma0_v_cm = (Conductivity_data.sigma0_veh * 0.01); 
Conductivity_data.sigma0_s_cm = (Conductivity_data.sigma0_struct * 0.01); 

% Average per loading
Summary_Table = groupsummary(Conductivity_data, "Loading", "mean", ...
    ["dH_kJmol", "dS_JmolK", "sigma0_v_cm", "sigma0_s_cm"])

return
%% Plot 1D PTFEL (Water + MOF overlaid, blue + red)

fprintf('\n=== Plotting 1D PTFEL ===\n');

plotting.plot_ptfel_1d(...
    PTFEL_data_processed, ...
    XLim=[-2, 2], ...
    YLim=[0, 12], ...
    Save=Save_plots, ...
    SaveDir=SaveDir_ptfel, ...
    FigSize=[800, 400], ...
    FontSize=16, ...
    LineWidth=2.5);

%% Plot 2D PTFEL Heatmaps

fprintf('\n=== Plotting 2D PTFEL ===\n');

plotting.plot_ptfel_2d(... 
    PTFEL_data_processed, ...
    XLim=[-1.5, 1.5], ...
    YLim=[2.2, 3.5], ...
    Colormap="turbo", ...
    Save=Save_plots, ...
    SaveDir=SaveDir_ptfel, ... 
    FigSize=[1000, 600], ...
    FontSize=20);

%% Plot DeltaG vs Temperature

fprintf('\n=== Plotting DeltaG vs Temperature ===\n');

plotting.plot_ptfel_gibbs_temp(...
    PTFEL_params, ...
    Type="water", ...
    Save=Save_plots, ...
    SaveDir=SaveDir_ptfel, ...
    FigSize=[800, 400], ...
    FontSize=16, ...
    LineWidth=1.5, ...
    MarkerSize=8);

%% Plot Conductivity

fprintf('\n=== Plotting Conductivity ===\n');

plotting.plot_conductivity(... 
    Conductivity_data, ... 
    PlotType="vs_temp", ...
    Scale="linear", ...
    Save=Save_plots, ...
    SaveDir=SaveDir_cond, ...
    FigSize=[800, 400], ...
    FontSize=16, ...
    LineWidth=1.5, ...
    MarkerSize=6);

%% Save Results

fprintf('\n=== Saving Results ===\n');

% Save PT-FEL parameters
if ~isfolder('results'), mkdir('results'); end
save('results/PTFEL_params.mat', 'PTFEL_params');
fprintf('PTFEL parameters saved to results/PTFEL_params.mat\n');

% Save conductivity data
save('results/Conductivity_params.mat', 'Conductivity_data');
fprintf('Conductivity data saved to results/Conductivity_params.mat\n');

%% Summary

fprintf('\n=== Summary ===\n');
fprintf('Water PTFEL: Mean DeltaG = %.2f ± %.2f kT\n', ...
       mean(PTFEL_params.dG_350K_kJmol(PTFEL_params.type == "water")), ...
       std(PTFEL_params.dG_350K_kJmol(PTFEL_params.type == "water")));
fprintf('MOF PTFEL: Mean DeltaG = %.2f ± %.2f kT\n', ... 
       mean(PTFEL_params.dG_350K_kJmol(PTFEL_params.type == "mof")), ...
       std(PTFEL_params.dG_350K_kJmol(PTFEL_params.type == "mof")));
fprintf('\nAnalysis Complete!\n');