%% RDF Analysis
% Radial Distribution Function analysis for water in MOF

clearvars
close all
clc

% Add paths
addpath(genpath("src"));

%% Variables

Save_plots = true;
SaveDir = "figures/rdf";

%% Load RDF Data

[RDF_data, Mol_values] = io.load_rdf_struct(...   
    "data/rdf", ... 
    Pattern="rdf_*.txt", ... 
    Verbose=true);

%% Common style options

style = {};...   
%     'FontSize', 12, ... 
%     'TitleFontSize', 14};

%% ===== INDIVIDUAL PLOTS =====
%% Plot Water RDF - Individual by Loading

plotting.plot_rdf(RDF_data, ["O-H", "O-O"], ...   
    GroupBy="loading", ...
    XLim=[1.25, 7], ...
    LineWidth=1.5, ...  
    Save=Save_plots, ...
    SaveDir=SaveDir, ...  
    Verbose=true);

%% Plot Water RDF - Individual by Temperature

plotting.plot_rdf(RDF_data, ["O-H", "O-O"], ...  
    GroupBy="temperature", ...
    XLim=[1.25, 7], ...
    LineWidth=1.5, ... 
    Save=Save_plots, ...
    SaveDir=SaveDir, ...  
    Verbose=true);

%% Plot Linker-Water RDF - Individual by Loading

plotting.plot_rdf(RDF_data, ["LinkerO-H", "LinkerO-O"], ... 
    GroupBy="loading", ...
    XLim=[0, 7], ...
    LegendLocation="northwest", ...
    LineWidth=1.5, ...  
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% Plot Linker-Water RDF - Individual by Temperature

plotting.plot_rdf(RDF_data, ["LinkerO-H", "LinkerO-O"], ... 
    GroupBy="temperature", ...
    XLim=[0, 7], ...
    LegendLocation="northwest", ...
    LineWidth=1.5, ... 
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% Plot Mu3-O-Water RDF - Individual by Loading

plotting.plot_rdf(RDF_data, ["Mu3O-H", "Mu3O-O"], ...  
    GroupBy="loading", ...
    XLim=[0, 7], ...
    LineWidth=1.5, ...  
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% Plot Mu3-O-Water RDF - Individual by Temperature

plotting.plot_rdf(RDF_data, ["Mu3O-H", "Mu3O-O"], ...  
    GroupBy="temperature", ...
    XLim=[0, 7], ...
    LineWidth=1.5, ... 
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% ===== COMBINED PLOTS (2by2 and 1by3) =====
%% Plot Water RDF - Combined by Loading (2by2)

plotting.plot_rdf_combined(RDF_data, ["O-H", "O-O"], ...  
    style{: }, ... 
    GroupBy="loading", ...
    XLim=[1.25, 7], ...
    LineWidth=1.0, ...  
    Save=Save_plots, ...
    SaveDir=SaveDir, ...  
    Verbose=true);

%% Plot Water RDF - Combined by Temperature (1by3)

plotting.plot_rdf_combined(RDF_data, ["O-H", "O-O"], ... 
    style{:}, ...
    GroupBy="temperature", ...
    XLim=[1.25, 7], ...
    LineWidth=1.0, ... 
    Save=Save_plots, ...
    SaveDir=SaveDir, ... 
    Verbose=true);

%% Plot Linker-Water RDF - Combined by Loading (2by2)

plotting.plot_rdf_combined(RDF_data, ["LinkerO-H", "LinkerO-O"], ... 
    style{:}, ... 
    GroupBy="loading", ...  
    XLim=[0, 7], ...  
    LineWidth=1.0, ... 
    FigureTitle="RDF - LinkerO and Water (by Loading)", ...
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% Plot Linker-Water RDF - Combined by Temperature (1by3)

plotting.plot_rdf_combined(RDF_data, ["LinkerO-H", "LinkerO-O"], ...  
    style{:}, ...  
    GroupBy="temperature", ... 
    XLim=[0, 7], ...  
    LineWidth=1.0, ... 
    FigureTitle="RDF - LinkerO and Water (by Temperature)", ...
    Save=Save_plots, ...
    SaveDir=SaveDir, ...
    Verbose=true);

%% Plot Mu3-Oxo-Water RDF - Combined by Loading (2by2)

plotting.plot_rdf_combined(RDF_data, ["Mu3O-H", "Mu3O-O"], ...  
    style{:}, ...  
    GroupBy="loading", ...
    XLim=[0, 7], ... 
    LineWidth=1.0, ... 
    FigureTitle="RDF - Mu3-O and Water (by Loading)", ...
    Save=Save_plots, ... 
    SaveDir=SaveDir, ... 
    Verbose=true);

%% Plot Mu3-Oxo-Water RDF - Combined by Temperature (1by3)

plotting.plot_rdf_combined(RDF_data, ["Mu3O-H", "Mu3O-O"], ...  
    style{:}, ...  
    GroupBy="temperature", ...
    XLim=[0, 7], ... 
    LineWidth=1.0, ...  
    FigureTitle="RDF - Mu3-O and Water (by Temperature)", ...
    Save=Save_plots, ... 
    SaveDir=SaveDir, ... 
    Verbose=true);